# Generated by Django 4.0.5 on 2022-06-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_ranjan'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('EmailField', models.EmailField(max_length=50)),
                ('Message', models.CharField(max_length=50)),
            ],
        ),
    ]
